//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetStockAnalyzer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BussinessCategory
    {
        public BussinessCategory()
        {
            this.Stock = new HashSet<Stock>();
        }
    
        public int BussinessCategoryId { get; set; }
        public string BussinessCategoryCode { get; set; }
        public string BussinessCategoryName { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
