//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetStockAnalyzer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : IEntity
    {
        public Company()
        {
            this.CompanyProductRelation = new HashSet<CompanyProductRelation>();
            this.Stocks = new HashSet<Stock>();
            this.CompanyScore = new HashSet<CompanyScore>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ParentCompanyId { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<CompanyProductRelation> CompanyProductRelation { get; set; }
        protected virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<CompanyScore> CompanyScore { get; set; }
    }
}
