//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetStockAnalyzer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : IEntity
    {
        public Product()
        {
            this.CompanyProductRelations = new HashSet<CompanyProductRelation>();
            this.SearchResults = new HashSet<SearchResult>();
            this.SearchWords = new HashSet<SearchWord>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("CompanyProductRelation")]
    	public virtual ICollection<CompanyProductRelation> CompanyProductRelations { get; set; }
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("SearchResult")]
    	public virtual ICollection<SearchResult> SearchResults { get; set; }
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("SearchWord")]
    	public virtual ICollection<SearchWord> SearchWords { get; set; }
    }
}
